//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_lam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bai_lam()
        {
            this.ct_bai_lam = new HashSet<ct_bai_lam>();
        }
    
        public int id_nguoi_lam { get; set; }
        public int id_bai_kt { get; set; }
        public Nullable<double> tong_diem { get; set; }
    
        public virtual bai_kiem_tra bai_kiem_tra { get; set; }
        public virtual tai_khoan tai_khoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_bai_lam> ct_bai_lam { get; set; }
    }
}
