//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_bai_kiem_tra
    {
        public int id_bkt { get; set; }
        public int id_cau_hoi { get; set; }
        public Nullable<int> thu_tu { get; set; }
    
        public virtual bai_kiem_tra bai_kiem_tra { get; set; }
        public virtual cau_hoi cau_hoi { get; set; }
    }
}
