//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_bai_lam
    {
        public int id_nguoi_lam { get; set; }
        public int id_bai_kt { get; set; }
        public int id_cau_hoi { get; set; }
        public string dap_an_chon { get; set; }
    
        public virtual bai_lam bai_lam { get; set; }
        public virtual cau_hoi cau_hoi { get; set; }
    }
}
